// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: borrow.proto

package buffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Borrow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	BorrowDate    string                 `protobuf:"bytes,5,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	DueDate       string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	ReturnDate    string                 `protobuf:"bytes,7,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Borrow) Reset() {
	*x = Borrow{}
	mi := &file_borrow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Borrow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrow) ProtoMessage() {}

func (x *Borrow) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrow.ProtoReflect.Descriptor instead.
func (*Borrow) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{0}
}

func (x *Borrow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Borrow) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Borrow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Borrow) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *Borrow) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *Borrow) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Borrow) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *Borrow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Borrow) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BorrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowRequest) Reset() {
	*x = BorrowRequest{}
	mi := &file_borrow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowRequest) ProtoMessage() {}

func (x *BorrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowRequest.ProtoReflect.Descriptor instead.
func (*BorrowRequest) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *BorrowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReturnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BorrowId      string                 `protobuf:"bytes,1,opt,name=borrow_id,json=borrowId,proto3" json:"borrow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnRequest) Reset() {
	*x = ReturnRequest{}
	mi := &file_borrow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnRequest) ProtoMessage() {}

func (x *ReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnRequest.ProtoReflect.Descriptor instead.
func (*ReturnRequest) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnRequest) GetBorrowId() string {
	if x != nil {
		return x.BorrowId
	}
	return ""
}

type BorrowServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Borrow        []*Borrow              `protobuf:"bytes,1,rep,name=borrow,proto3" json:"borrow,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowServiceResponse) Reset() {
	*x = BorrowServiceResponse{}
	mi := &file_borrow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowServiceResponse) ProtoMessage() {}

func (x *BorrowServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowServiceResponse.ProtoReflect.Descriptor instead.
func (*BorrowServiceResponse) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{3}
}

func (x *BorrowServiceResponse) GetBorrow() []*Borrow {
	if x != nil {
		return x.Borrow
	}
	return nil
}

func (x *BorrowServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BorrowServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_borrow_proto protoreflect.FileDescriptor

const file_borrow_proto_rawDesc = "" +
	"\n" +
	"\fborrow.proto\x12\x06shared\"\x8a\x02\n" +
	"\x06Borrow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rcollection_id\x18\x04 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vborrow_date\x18\x05 \x01(\tR\n" +
	"borrowDate\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x1f\n" +
	"\vreturn_date\x18\a \x01(\tR\n" +
	"returnDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"M\n" +
	"\rBorrowRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\rReturnRequest\x12\x1b\n" +
	"\tborrow_id\x18\x01 \x01(\tR\bborrowId\"s\n" +
	"\x15BorrowServiceResponse\x12&\n" +
	"\x06borrow\x18\x01 \x03(\v2\x0e.shared.BorrowR\x06borrow\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\x97\x01\n" +
	"\rBorrowService\x12B\n" +
	"\n" +
	"BorrowBook\x12\x15.shared.BorrowRequest\x1a\x1d.shared.BorrowServiceResponse\x12B\n" +
	"\n" +
	"ReturnBook\x12\x15.shared.ReturnRequest\x1a\x1d.shared.BorrowServiceResponseB\n" +
	"Z\b./bufferb\x06proto3"

var (
	file_borrow_proto_rawDescOnce sync.Once
	file_borrow_proto_rawDescData []byte
)

func file_borrow_proto_rawDescGZIP() []byte {
	file_borrow_proto_rawDescOnce.Do(func() {
		file_borrow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_borrow_proto_rawDesc), len(file_borrow_proto_rawDesc)))
	})
	return file_borrow_proto_rawDescData
}

var file_borrow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_borrow_proto_goTypes = []any{
	(*Borrow)(nil),                // 0: shared.Borrow
	(*BorrowRequest)(nil),         // 1: shared.BorrowRequest
	(*ReturnRequest)(nil),         // 2: shared.ReturnRequest
	(*BorrowServiceResponse)(nil), // 3: shared.BorrowServiceResponse
}
var file_borrow_proto_depIdxs = []int32{
	0, // 0: shared.BorrowServiceResponse.borrow:type_name -> shared.Borrow
	1, // 1: shared.BorrowService.BorrowBook:input_type -> shared.BorrowRequest
	2, // 2: shared.BorrowService.ReturnBook:input_type -> shared.ReturnRequest
	3, // 3: shared.BorrowService.BorrowBook:output_type -> shared.BorrowServiceResponse
	3, // 4: shared.BorrowService.ReturnBook:output_type -> shared.BorrowServiceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_borrow_proto_init() }
func file_borrow_proto_init() {
	if File_borrow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_borrow_proto_rawDesc), len(file_borrow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_borrow_proto_goTypes,
		DependencyIndexes: file_borrow_proto_depIdxs,
		MessageInfos:      file_borrow_proto_msgTypes,
	}.Build()
	File_borrow_proto = out.File
	file_borrow_proto_goTypes = nil
	file_borrow_proto_depIdxs = nil
}
