// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: collection.proto

package buffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author         string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Categories     []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	TotalBooks     int32                  `protobuf:"varint,5,opt,name=total_books,json=totalBooks,proto3" json:"total_books,omitempty"`
	AvailableBooks int32                  `protobuf:"varint,6,opt,name=available_books,json=availableBooks,proto3" json:"available_books,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Collection) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Collection) GetTotalBooks() int32 {
	if x != nil {
		return x.TotalBooks
	}
	return 0
}

func (x *Collection) GetAvailableBooks() int32 {
	if x != nil {
		return x.AvailableBooks
	}
	return 0
}

func (x *Collection) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Collection) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    []*Collection          `protobuf:"bytes,1,rep,name=collection,proto3" json:"collection,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCollection() []*Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get Collection messages
type GetCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Author         *string                `protobuf:"bytes,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Categories     []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	TotalBooks     *int32                 `protobuf:"varint,5,opt,name=total_books,json=totalBooks,proto3,oneof" json:"total_books,omitempty"`
	AvailableBooks *int32                 `protobuf:"varint,6,opt,name=available_books,json=availableBooks,proto3,oneof" json:"available_books,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{2}
}

func (x *GetCollectionRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetCollectionRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *GetCollectionRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCollectionRequest) GetTotalBooks() int32 {
	if x != nil && x.TotalBooks != nil {
		return *x.TotalBooks
	}
	return 0
}

func (x *GetCollectionRequest) GetAvailableBooks() int32 {
	if x != nil && x.AvailableBooks != nil {
		return *x.AvailableBooks
	}
	return 0
}

// Find Collection messages
type FindCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCollectionRequest) Reset() {
	*x = FindCollectionRequest{}
	mi := &file_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCollectionRequest) ProtoMessage() {}

func (x *FindCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCollectionRequest.ProtoReflect.Descriptor instead.
func (*FindCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{3}
}

func (x *FindCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Add Collection messages
type AddCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollectionRequest) Reset() {
	*x = AddCollectionRequest{}
	mi := &file_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollectionRequest) ProtoMessage() {}

func (x *AddCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollectionRequest.ProtoReflect.Descriptor instead.
func (*AddCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{4}
}

func (x *AddCollectionRequest) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// Update Collection messages
type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Delete Collection messages
type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DecrementAvailableBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementAvailableBooksRequest) Reset() {
	*x = DecrementAvailableBooksRequest{}
	mi := &file_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementAvailableBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementAvailableBooksRequest) ProtoMessage() {}

func (x *DecrementAvailableBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementAvailableBooksRequest.ProtoReflect.Descriptor instead.
func (*DecrementAvailableBooksRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{7}
}

func (x *DecrementAvailableBooksRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecrementAvailableBooksRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_collection_proto protoreflect.FileDescriptor

const file_collection_proto_rawDesc = "" +
	"\n" +
	"\x10collection.proto\x12\x06shared\x1a\x1cgoogle/protobuf/struct.proto\"\xf0\x01\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x1f\n" +
	"\vtotal_books\x18\x05 \x01(\x05R\n" +
	"totalBooks\x12'\n" +
	"\x0favailable_books\x18\x06 \x01(\x05R\x0eavailableBooks\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"r\n" +
	"\bResponse\x122\n" +
	"\n" +
	"collection\x18\x01 \x03(\v2\x12.shared.CollectionR\n" +
	"collection\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xf8\x01\n" +
	"\x14GetCollectionRequest\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x03 \x01(\tH\x01R\x06author\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12$\n" +
	"\vtotal_books\x18\x05 \x01(\x05H\x02R\n" +
	"totalBooks\x88\x01\x01\x12,\n" +
	"\x0favailable_books\x18\x06 \x01(\x05H\x03R\x0eavailableBooks\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_authorB\x0e\n" +
	"\f_total_booksB\x12\n" +
	"\x10_available_books\"'\n" +
	"\x15FindCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14AddCollectionRequest\x122\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x12.shared.CollectionR\n" +
	"collection\"\\\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\")\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x1eDecrementAvailableBooksRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount2\xbf\x03\n" +
	"\x11CollectionService\x12?\n" +
	"\rGetCollection\x12\x1c.shared.GetCollectionRequest\x1a\x10.shared.Response\x12E\n" +
	"\x12FindCollectionById\x12\x1d.shared.FindCollectionRequest\x1a\x10.shared.Response\x12?\n" +
	"\rAddCollection\x12\x1c.shared.AddCollectionRequest\x1a\x10.shared.Response\x12E\n" +
	"\x10UpdateCollection\x12\x1f.shared.UpdateCollectionRequest\x1a\x10.shared.Response\x12E\n" +
	"\x10DeleteCollection\x12\x1f.shared.DeleteCollectionRequest\x1a\x10.shared.Response\x12S\n" +
	"\x17DecrementAvailableBooks\x12&.shared.DecrementAvailableBooksRequest\x1a\x10.shared.ResponseB\n" +
	"Z\b./bufferb\x06proto3"

var (
	file_collection_proto_rawDescOnce sync.Once
	file_collection_proto_rawDescData []byte
)

func file_collection_proto_rawDescGZIP() []byte {
	file_collection_proto_rawDescOnce.Do(func() {
		file_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)))
	})
	return file_collection_proto_rawDescData
}

var file_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_collection_proto_goTypes = []any{
	(*Collection)(nil),                     // 0: shared.Collection
	(*Response)(nil),                       // 1: shared.Response
	(*GetCollectionRequest)(nil),           // 2: shared.GetCollectionRequest
	(*FindCollectionRequest)(nil),          // 3: shared.FindCollectionRequest
	(*AddCollectionRequest)(nil),           // 4: shared.AddCollectionRequest
	(*UpdateCollectionRequest)(nil),        // 5: shared.UpdateCollectionRequest
	(*DeleteCollectionRequest)(nil),        // 6: shared.DeleteCollectionRequest
	(*DecrementAvailableBooksRequest)(nil), // 7: shared.DecrementAvailableBooksRequest
	(*structpb.Struct)(nil),                // 8: google.protobuf.Struct
}
var file_collection_proto_depIdxs = []int32{
	0, // 0: shared.Response.collection:type_name -> shared.Collection
	0, // 1: shared.AddCollectionRequest.collection:type_name -> shared.Collection
	8, // 2: shared.UpdateCollectionRequest.payload:type_name -> google.protobuf.Struct
	2, // 3: shared.CollectionService.GetCollection:input_type -> shared.GetCollectionRequest
	3, // 4: shared.CollectionService.FindCollectionById:input_type -> shared.FindCollectionRequest
	4, // 5: shared.CollectionService.AddCollection:input_type -> shared.AddCollectionRequest
	5, // 6: shared.CollectionService.UpdateCollection:input_type -> shared.UpdateCollectionRequest
	6, // 7: shared.CollectionService.DeleteCollection:input_type -> shared.DeleteCollectionRequest
	7, // 8: shared.CollectionService.DecrementAvailableBooks:input_type -> shared.DecrementAvailableBooksRequest
	1, // 9: shared.CollectionService.GetCollection:output_type -> shared.Response
	1, // 10: shared.CollectionService.FindCollectionById:output_type -> shared.Response
	1, // 11: shared.CollectionService.AddCollection:output_type -> shared.Response
	1, // 12: shared.CollectionService.UpdateCollection:output_type -> shared.Response
	1, // 13: shared.CollectionService.DeleteCollection:output_type -> shared.Response
	1, // 14: shared.CollectionService.DecrementAvailableBooks:output_type -> shared.Response
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_collection_proto_init() }
func file_collection_proto_init() {
	if File_collection_proto != nil {
		return
	}
	file_collection_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collection_proto_goTypes,
		DependencyIndexes: file_collection_proto_depIdxs,
		MessageInfos:      file_collection_proto_msgTypes,
	}.Build()
	File_collection_proto = out.File
	file_collection_proto_goTypes = nil
	file_collection_proto_depIdxs = nil
}
